### ISSUE TITLE
Variable name breaks vcf2fasta

### ISSUE THREAD

**Issue by antunderwood** [phe-bioinformatics/PHEnix#16]
When I run vcf2fasta.py I get the following error

Traceback (most recent call last):
  File "/home/anthony.underwood/galaxy/tool_dependencies/phephenix/1.0/ulfschaefer/package_phephenix_1_0/214560c61f1d/scripts/phenix.py", line 96, in <module>
    exit(main())
  File "/home/anthony.underwood/galaxy/tool_dependencies/phephenix/1.0/ulfschaefer/package_phephenix_1_0/214560c61f1d/scripts/phenix.py", line 91, in main
    return vcf2fasta.main(args)
  File "/home/anthony.underwood/galaxy/tool_dependencies/phephenix/1.0/ulfschaefer/package_phephenix_1_0/214560c61f1d/scripts/vcf2fasta.py", line 471, in main
    if sample == "reference":
UnboundLocalError: local variable 'sample' referenced before assignment

I think the variable name in line 471 should be sample_name not sample.

https://github.com/phe-bioinformatics/PHEnix/blob/master/scripts/vcf2fasta.py#L471

**Comment by alexjironkin** [comment]
Fixed
